/* The emoji the picker offers.
 *
 * A curated list rather than the whole Unicode set: `emoji-picker-react`
 * shipped every emoji in existence behind a search box, which is 1,800 rows of
 * things nobody has ever put on a Discord button and about 400 KB of JavaScript
 * to hold them. What a message actually uses is a few hundred, and a picker
 * short enough to scan beats one long enough to need searching.
 *
 * Grouped the way Discord groups them, in Discord's order, with the keywords
 * somebody would actually type.
 */

export const EMOJI_GROUPS = [
  {
    id: "people",
    name: "People",
    icon: "😀",
    emoji: [
      ["😀", "grin smile happy"], ["😃", "smile happy"], ["😄", "smile happy laugh"],
      ["😁", "beam grin"], ["😆", "laugh satisfied"], ["😅", "sweat laugh"],
      ["🤣", "rofl rolling laugh"], ["😂", "joy tears laugh"], ["🙂", "slight smile"],
      ["🙃", "upside down"], ["😉", "wink"], ["😊", "blush smile"], ["😇", "innocent halo"],
      ["🥰", "hearts love"], ["😍", "heart eyes love"], ["🤩", "star struck"],
      ["😘", "kiss"], ["😗", "kissing"], ["😚", "kissing closed"], ["😙", "kissing smile"],
      ["🥲", "tear smile"], ["😋", "yum tasty"], ["😛", "tongue"], ["😜", "wink tongue"],
      ["🤪", "zany goofy"], ["😝", "squint tongue"], ["🤑", "money"], ["🤗", "hug"],
      ["🤭", "hand over mouth oops"], ["🤫", "shush quiet"], ["🤔", "thinking hmm"],
      ["🤐", "zipper quiet"], ["🤨", "raised eyebrow suspicious"], ["😐", "neutral"],
      ["😑", "expressionless"], ["😶", "no mouth"], ["😏", "smirk"], ["😒", "unamused"],
      ["🙄", "eye roll"], ["😬", "grimace"], ["🤥", "lying"], ["😌", "relieved"],
      ["😔", "pensive sad"], ["😪", "sleepy"], ["🤤", "drool"], ["😴", "sleep zzz"],
      ["😷", "mask sick"], ["🤒", "thermometer sick"], ["🤕", "bandage hurt"],
      ["🥵", "hot"], ["🥶", "cold freezing"], ["😵", "dizzy"], ["🤯", "mind blown"],
      ["🤠", "cowboy"], ["🥳", "party celebrate"], ["😎", "sunglasses cool"],
      ["🤓", "nerd"], ["🧐", "monocle"], ["😕", "confused"], ["😟", "worried"],
      ["🙁", "frown"], ["😮", "open mouth"], ["😯", "hushed"], ["😲", "astonished"],
      ["😳", "flushed"], ["🥺", "pleading"], ["😦", "frowning"], ["😧", "anguished"],
      ["😨", "fearful"], ["😰", "anxious sweat"], ["😥", "sad relieved"], ["😢", "cry"],
      ["😭", "sob cry"], ["😱", "scream"], ["😖", "confounded"], ["😣", "persevere"],
      ["😞", "disappointed"], ["😓", "downcast sweat"], ["😩", "weary"], ["😫", "tired"],
      ["🥱", "yawn"], ["😤", "triumph steam"], ["😡", "rage angry"], ["😠", "angry"],
      ["🤬", "cursing swear"], ["😈", "devil"], ["👿", "imp angry"], ["💀", "skull dead"],
      ["☠️", "skull crossbones"], ["💩", "poop"], ["🤡", "clown"], ["👻", "ghost"],
      ["👽", "alien"], ["🤖", "robot bot"], ["🎃", "pumpkin halloween"],
      ["🫡", "salute"], ["🫠", "melting"], ["🫢", "gasp"], ["🥹", "holding back tears"],
    ],
  },
  {
    id: "gestures",
    name: "Gestures",
    icon: "👍",
    emoji: [
      ["👍", "thumbs up yes approve"], ["👎", "thumbs down no"], ["👌", "ok"],
      ["🤌", "pinched"], ["✌️", "victory peace"], ["🤞", "crossed fingers luck"],
      ["🤟", "love you"], ["🤘", "rock horns"], ["🤙", "call me"], ["👈", "left"],
      ["👉", "right"], ["👆", "up"], ["👇", "down"], ["☝️", "index up"],
      ["✋", "raised hand stop"], ["🤚", "back of hand"], ["🖐️", "splayed"],
      ["🖖", "vulcan"], ["👋", "wave hello hi bye"], ["🤝", "handshake deal"],
      ["🙏", "pray thanks please"], ["✍️", "writing"], ["💪", "muscle strong"],
      ["🦾", "mechanical arm"], ["🙌", "raised hands celebrate"], ["👏", "clap"],
      ["🫶", "heart hands"], ["🫰", "finger heart"], ["👊", "fist bump"],
      ["✊", "raised fist"], ["🤛", "left fist"], ["🤜", "right fist"],
      ["🧠", "brain"], ["👀", "eyes look"], ["👁️", "eye"], ["🫵", "point you"],
    ],
  },
  {
    id: "nature",
    name: "Nature",
    icon: "🐊",
    emoji: [
      ["🐊", "crocodile alligator gator"], ["🦎", "lizard"], ["🐢", "turtle"],
      ["🐍", "snake"], ["🐉", "dragon"], ["🦕", "dinosaur"], ["🐶", "dog puppy"],
      ["🐱", "cat"], ["🐭", "mouse"], ["🐹", "hamster"], ["🐰", "rabbit"],
      ["🦊", "fox"], ["🐻", "bear"], ["🐼", "panda"], ["🐨", "koala"], ["🐯", "tiger"],
      ["🦁", "lion"], ["🐮", "cow"], ["🐷", "pig"], ["🐸", "frog"], ["🐵", "monkey"],
      ["🐔", "chicken"], ["🐧", "penguin"], ["🐦", "bird"], ["🦆", "duck"],
      ["🦅", "eagle"], ["🦉", "owl"], ["🐺", "wolf"], ["🐗", "boar"], ["🐴", "horse"],
      ["🦄", "unicorn"], ["🐝", "bee"], ["🦋", "butterfly"], ["🐙", "octopus"],
      ["🦈", "shark"], ["🐬", "dolphin"], ["🐳", "whale"], ["🐟", "fish"],
      ["🌲", "tree"], ["🌴", "palm"], ["🌵", "cactus"], ["🌸", "blossom"],
      ["🌹", "rose"], ["🌻", "sunflower"], ["🍀", "clover luck"], ["🍁", "maple"],
      ["🔥", "fire lit hot"], ["⭐", "star"], ["🌟", "glowing star"], ["✨", "sparkles"],
      ["⚡", "zap lightning"], ["🌈", "rainbow"], ["☀️", "sun"], ["🌙", "moon"],
      ["☁️", "cloud"], ["🌧️", "rain"], ["❄️", "snow cold"], ["💧", "droplet"],
      ["🌊", "wave ocean"],
    ],
  },
  {
    id: "food",
    name: "Food",
    icon: "🍕",
    emoji: [
      ["🍏", "apple green"], ["🍎", "apple"], ["🍊", "orange"], ["🍋", "lemon"],
      ["🍌", "banana"], ["🍉", "watermelon"], ["🍇", "grapes"], ["🍓", "strawberry"],
      ["🫐", "blueberries"], ["🍒", "cherries"], ["🍑", "peach"], ["🥭", "mango"],
      ["🍍", "pineapple"], ["🥥", "coconut"], ["🥑", "avocado"], ["🍅", "tomato"],
      ["🌽", "corn"], ["🥕", "carrot"], ["🥔", "potato"], ["🍞", "bread"],
      ["🥐", "croissant"], ["🧀", "cheese"], ["🥓", "bacon"], ["🍔", "burger"],
      ["🍟", "fries"], ["🍕", "pizza"], ["🌭", "hotdog"], ["🌮", "taco"],
      ["🌯", "burrito"], ["🥗", "salad"], ["🍝", "pasta"], ["🍜", "ramen"],
      ["🍣", "sushi"], ["🍦", "ice cream"], ["🍩", "donut"], ["🍪", "cookie"],
      ["🎂", "cake birthday"], ["🍫", "chocolate"], ["🍬", "candy"], ["🍿", "popcorn"],
      ["☕", "coffee"], ["🍵", "tea"], ["🧃", "juice"], ["🥤", "soda"],
      ["🍺", "beer"], ["🍻", "cheers"], ["🥂", "champagne"], ["🍷", "wine"],
    ],
  },
  {
    id: "activity",
    name: "Activity",
    icon: "⚽",
    emoji: [
      ["⚽", "football soccer"], ["🏀", "basketball"], ["🏈", "american football"],
      ["⚾", "baseball"], ["🎾", "tennis"], ["🏐", "volleyball"], ["🎱", "8ball pool"],
      ["🏓", "ping pong"], ["🏸", "badminton"], ["🥅", "goal"], ["⛳", "golf"],
      ["🏹", "archery bow"], ["🎣", "fishing"], ["🥊", "boxing"], ["🎯", "target dart"],
      ["🎮", "gaming controller"], ["🕹️", "joystick"], ["🎲", "dice"], ["♟️", "chess"],
      ["🎨", "art paint"], ["🎬", "movie clapper"], ["🎤", "mic sing"],
      ["🎧", "headphones"], ["🎵", "music note"], ["🎶", "music notes"],
      ["🎸", "guitar"], ["🥁", "drum"], ["🎹", "piano"], ["🏆", "trophy win"],
      ["🥇", "gold medal first"], ["🥈", "silver second"], ["🥉", "bronze third"],
      ["🎖️", "medal"], ["🎗️", "ribbon"], ["🎉", "tada party celebrate"],
      ["🎊", "confetti"], ["🎈", "balloon"], ["🎁", "gift present"],
    ],
  },
  {
    id: "objects",
    name: "Objects",
    icon: "💻",
    emoji: [
      ["💻", "laptop computer"], ["🖥️", "desktop"], ["⌨️", "keyboard"],
      ["🖱️", "mouse"], ["📱", "phone mobile"], ["☎️", "telephone"], ["📞", "call"],
      ["📷", "camera"], ["📹", "video"], ["🎥", "movie camera"], ["📺", "tv"],
      ["🔋", "battery"], ["🔌", "plug"], ["💡", "bulb idea"], ["🔦", "torch"],
      ["🕯️", "candle"], ["📖", "book"], ["📚", "books"], ["📝", "memo note"],
      ["📄", "page document"], ["📋", "clipboard list"], ["📌", "pin"],
      ["📎", "paperclip"], ["✂️", "scissors"], ["🔑", "key"], ["🔒", "lock"],
      ["🔓", "unlock"], ["🔨", "hammer"], ["🔧", "wrench"], ["⚙️", "gear settings"],
      ["🛠️", "tools"], ["🧰", "toolbox"], ["⚖️", "scales justice"],
      ["🔗", "link chain"], ["📦", "package box"], ["📮", "mailbox"],
      ["✉️", "envelope mail"], ["📧", "email"], ["💰", "money bag"],
      ["💳", "credit card"], ["💎", "gem diamond"], ["🏷️", "tag label"],
      ["🔔", "bell notify"], ["🔕", "bell off mute"], ["📢", "announce loud"],
      ["📣", "megaphone"], ["🗓️", "calendar"], ["⏰", "alarm clock"],
      ["⏳", "hourglass"], ["🧭", "compass"], ["🗑️", "trash delete"],
      ["🛡️", "shield"], ["⚔️", "swords"], ["🎫", "ticket"], ["🎟️", "admission ticket"],
    ],
  },
  {
    id: "symbols",
    name: "Symbols",
    icon: "❤️",
    emoji: [
      ["❤️", "red heart love"], ["🧡", "orange heart"], ["💛", "yellow heart"],
      ["💚", "green heart"], ["💙", "blue heart"], ["💜", "purple heart"],
      ["🖤", "black heart"], ["🤍", "white heart"], ["🤎", "brown heart"],
      ["💔", "broken heart"], ["💕", "two hearts"], ["💖", "sparkling heart"],
      ["💗", "growing heart"], ["💘", "heart arrow"], ["💝", "heart ribbon"],
      ["✅", "check tick yes done"], ["☑️", "ballot check"], ["✔️", "check mark"],
      ["❌", "cross no wrong"], ["❎", "cross mark button"], ["⭕", "circle"],
      ["🚫", "prohibited no"], ["⚠️", "warning caution"], ["❗", "exclamation"],
      ["❓", "question"], ["💯", "hundred perfect"], ["🔴", "red circle"],
      ["🟠", "orange circle"], ["🟡", "yellow circle"], ["🟢", "green circle"],
      ["🔵", "blue circle"], ["🟣", "purple circle"], ["⚫", "black circle"],
      ["⚪", "white circle"], ["🟥", "red square"], ["🟧", "orange square"],
      ["🟨", "yellow square"], ["🟩", "green square"], ["🟦", "blue square"],
      ["🟪", "purple square"], ["⬛", "black square"], ["⬜", "white square"],
      ["🔺", "red triangle up"], ["🔻", "red triangle down"], ["🔶", "orange diamond"],
      ["➡️", "right arrow"], ["⬅️", "left arrow"], ["⬆️", "up arrow"],
      ["⬇️", "down arrow"], ["🔄", "refresh sync"], ["🔁", "repeat"],
      ["▶️", "play"], ["⏸️", "pause"], ["⏹️", "stop"], ["⏭️", "next"],
      ["🆕", "new"], ["🆓", "free"], ["🔞", "eighteen"], ["♻️", "recycle"],
      ["🏁", "checkered flag"], ["🚩", "triangular flag"], ["🏳️", "white flag"],
    ],
  },
];

/** Every emoji, flat, for search. */
export const ALL_EMOJI = EMOJI_GROUPS.flatMap((g) =>
  g.emoji.map(([char, keywords]) => ({ char, keywords, group: g.id })),
);
